// @ts-check
/** @type {import("@ianvs/prettier-plugin-sort-imports").PrettierConfig} */
module.exports = {
	"arrowParens": "always",
	"bracketSameLine": true,
	"bracketSpacing": true,
	"embeddedLanguageFormatting": "auto",
	"endOfLine": "lf",
	"htmlWhitespaceSensitivity": "css",
	"insertPragma": false,
	"jsxSingleQuote": false,
	"printWidth": 80,
	"proseWrap": "preserve",
	"quoteProps": "as-needed",
	"requirePragma": false,
	"semi": false,
	"singleQuote": true,
	"trailingComma": "es5",
	"vueIndentScriptAndStyle": false,
	"tabWidth": 3,
	"useTabs": true,
	"plugins": [
		"@ianvs/prettier-plugin-sort-imports",
		"prettier-plugin-tailwindcss",
	],
	"importOrder": ["^[~/]", "^[./]"],
	"importOrderBuiltinModulesToTop": true,
	"importOrderCaseInsensitive": true,
	"importOrderParserPlugins": ["typescript", "jsx", "decorators-legacy"],
	"importOrderMergeDuplicateImports": true,
	"importOrderCombineTypeAndValueImports": true,
	"importOrderSeparation": true,
	"importOrderSortSpecifiers": true,
}
